### ISSUE TITLE
ChromeOS 125-130 not found

### ISSUE THREAD

**Issue by baseattackforce** [rainestorme/murkmod#103] opened 2024-11-08 17:07 UTC
**Describe the bug**
When trying to use "custom milestone" and selecting anything from 125-130, the script will fail to find it and end itself.

**To Reproduce**
1. Open murkmod's devmode installer
2. Click on "custom milestone"
3. Select anything from 125-130
4. It fails

**Expected behavior**
The images should successfully download, but are not found

**Screenshots**
Unable to take a picture of vt2 as of now, but it shows that it is "reverting to chromiumos source" but is still unable to find the image.

**System (please complete the following information):**
 - Dedede
 - v130
- devmode installer

**Additional context**
I believe there are different reasons for this problem.
For 127-130 they are not indexed on Chrome100, but for 125-126 the issue is simply that rainestorme didnt update the file it calls from (why cant it just call from chrome100)

**HOW TO FIX**
Method 1: Update [the source link](https://raw.githubusercontent.com/rainestorme/chrome100-json/refs/heads/main/boards/dedede.json) to support 125-130
Method 2: If someone else is having this issue and wants to fix it themselves, they can fork murkmod and chrome100-json and modify "LOCAL_URL" to their chrome100-json fork and inside that add the index for newer versions on your board.

I fixed mine with method 2, but it was quite irritating and I recommend this issue be fixed.

**Comment by Eboi47** [comment] 2024-11-09 22:03
This version isn't on chrome100, which is the reason for the issue, but it should be available on the chromium dash website, so this is an is an issue with obtaining recovery files from chromium dash

**Comment by Eboi47** [comment] 2024-11-10 19:49
https://github.com/rainestorme/murkmod/issues/103#issuecomment-2466813197 did you reboot  in between attempts when attempting these versions? This may be the cause of other errors.

**Comment by Packjackisback** [comment] 2024-11-10 23:05
Make a pull request if you have fixed the issue manually

**Comment by rainestorme** [comment] 2024-11-11 14:38
Should most likely be closed by #100, and will be fixed by rainestorme/chrome100-json#1.

**Comment by rainestorme** [comment] 2024-11-11 20:02
chrome100-json is now fixed, and supports up to v126 - Chromium Dash is yet to be fixed.

**Closed** 2024-11-11 20:02 UTC
