### ISSUE TITLE
No Bootable Kernel Found

### ISSUE THREAD

**Issue by Packjackisback** [rainestorme/murkmod#106] opened 2024-11-12 17:03 UTC
**Describe the bug**
After install, I got the "no bootable kernel found" screen, and when I went to the reco screen I got the reason "No bootable kernel found"

**System (please complete the following information):**
 - Board: octopus
 - Version: 130
- Installation method used: devmode installer

**Comment by Eboi47** [comment] 2024-11-12 17:15
I would just recover the Chromebook and try murkmodding again. If that doesn't work then record the terminal output during installation and put it here.

**Comment by Packjackisback** [comment] 2024-11-12 17:16
Yeah that was the second time, I'm gonna try one more time, then run it without wp tonight

**Comment by Packjackisback** [comment] 2024-11-12 17:17
iirc the only error was the wp error for the flag change, but I worry this could be related to the recent changes.

**Comment by rainestorme** [comment] 2024-11-12 20:21
Fascinating... I have no idea what could cause this but I can check codesearch to try to traceback the error a bit.

**Comment by rainestorme** [comment] 2024-11-12 20:24
Looks to be able to be traced back to `2recovery_reasons.c`:
https://source.chromium.org/chromiumos/chromiumos/codesearch/+/main:src/platform/vboot_reference/firmware/2lib/2recovery_reasons.c?q=%22No%20bootable%20kernel%20found%22&ss=chromiumos%2Fchromiumos%2Fcodesearch
Here's all the potential places where this could be raised:
https://source.chromium.org/search?q=%22VB2_RECOVERY_RW_NO_KERNEL%22&sq=&ss=chromiumos%2Fchromiumos%2Fcodesearch

**Comment by Packjackisback** [comment] 2024-11-12 20:24
Running it again rn, it is overwriting rn with no errors so far

**Comment by Packjackisback** [comment] 2024-11-12 20:25
I'm wondering if it stems from how I am accessing devmode

**Comment by rainestorme** [comment] 2024-11-12 20:26
You may be able to extract some log information from the stateful partition. If this error occurs again, can you boot into SH1mmer immediately after and check `/mnt/stateful_partition` for logs?

**Comment by Packjackisback** [comment] 2024-11-12 20:27
I got a ton of flashrom errors at the end.

**Comment by Packjackisback** [comment] 2024-11-12 20:27
booted this time, we'll see if it persists

**Comment by rainestorme** [comment] 2024-11-12 20:27
> I got a ton of flashrom errors at the end.

To be expected if WP is enabled.

**Comment by Packjackisback** [comment] 2024-11-12 20:29
Hmm, hanged on boot and then went back to the transitioning to developer screen. Assuming this is intended behaviour?

**Comment by rainestorme** [comment] 2024-11-12 20:29
Again, tracing it back in codesearch, the most critical file seems to be [here](https://source.chromium.org/chromiumos/chromiumos/codesearch/+/main:src/platform/vboot_reference/firmware/2lib/2load_kernel.c?q=%22VB2_ERROR_LK_NO_KERNEL_FOUND%22&ss=chromiumos%2Fchromiumos%2Fcodesearch). If I had to guess, this just has something to do with how verity is disabled during the image patching process.

**Comment by rainestorme** [comment] 2024-11-12 20:30
> Hmm, hanged on boot and then went back to the transitioning to developer screen. Assuming this is intended behaviour?

Intended behaviour.

**Comment by Packjackisback** [comment] 2024-11-12 20:30
I don't feel like finding a proxy rn, but I'll check chromium and try and figure it out in appx 5 minutes

**Comment by rainestorme** [comment] 2024-11-13 13:16
No, I'll leave it open incase someone else can repro.

**Comment by rainestorme** [comment] 2024-12-03 20:57
Closing since nobody can repro.

**Closed by rainestorme** 2024-12-03 20:57 UTC
Labels: bug
