### ISSUE TITLE
failed to create loop partition

### ISSUE THREAD

**Issue by coolestDude19** [rainestorme/murkmod#93] opened 2024-10-11 22:32 UTC
**Describe the bug**
After the devmode installer finishes downloading the chromeOS recovery image, it fails when it tries to create a loop partition

**To Reproduce**
1. Go to 'the devmode installer'
2. Click on 'any option'
3. Wait for it to 'finish downloading the recovery image'

**Expected behavior**
I expected it to create a loop partition and install murkmod successfully

**Screenshots**
In comments

**System**
 - Board [octopus]
 - Version [newest]
- Installation method used [devmode installer]

**Additional context**
None

**Comment by coolestDude19** [comment] 2024-10-11 22:41
![IMG_20241011_18344082](https://github.com/user-attachments/assets/635a5d00-ea95-4723-b861-17e51f1d1ec7)

**Comment by rainestorme** [comment] 2024-10-12 13:54
I'm not sure what could cause this issue, can you run `fdisk -l` and `losetup -f` and send over the outputs?

**Comment by coolestDude19** [comment] 2024-10-12 17:14
![IMG_20241012_13084050](https://github.com/user-attachments/assets/2341d093-e234-4e12-be2e-7affa3108177)
![IMG_20241012_13085857](https://github.com/user-attachments/assets/657ebd5b-f5dc-49b8-9789-a05b6deb3732)

**Comment by rainestorme** [comment] 2024-10-15 16:45
Interesting. Your losetup appears to be printing `FINDING FREE!!!`, which is absolutely **not** supposed to happen. I have no idea what could possibly cause this, and testing on my own octopus device yields no result. Seeing as I can't reproduce this, I'll close this issue. If someone else has the same problem, please comment.

**Comment by coolestDude19** [comment] 2024-10-15 22:18
Ok. I'll try a few things to see if I can fix that but thanks for the help.

**Comment by ifee11ikeiediagcmdrn** [comment] 2024-10-15 22:29
I do not know. Maybe try again, but, if it doesnt work then just use regular shimboot.

**Comment by ifee11ikeiediagcmdrn** [comment] 2024-10-15 22:29
Download another modern octopus?

**Comment by ifee11ikeiediagcmdrn** [comment] 2024-10-15 22:30
im gay. *not*

**Comment by kingofnetflix** [comment] 2024-11-10 03:20
having this same issue (octopus fleex on v130)

**Comment by rainestorme** [comment] 2024-11-11 14:36
Anyone having this issue - please run `losetup -f` and post the exact text of the results. You can most likely accomplish this with these commands (in vt2, as root, **after** logging into the system):

```sh
touch /home/chronos/user/Downloads/losetup_output.txt
losetup -f > /home/chronos/user/Downloads/losetup_output.txt
chmod 777 /home/chronos/user/Downloads/losetup_output.txt
```

Then the output file will be in your Downloads folder which you can upload here. This is only necessary because I need to be able to see the exact spacing that's used by this quirky little implementation of `losetup` - I can't find any instance of this in the main util-linux repo.

**Comment by kingofnetflix** [comment] 2024-11-11 16:16
> Anyone having this issue - please run `losetup -f` and post the exact text of the results. You can most likely accomplish this with these commands (in vt2, as root, **after** logging into the system):
> 
> ```shell
> touch /home/chronos/user/Downloads/losetup_output.txt
> losetup -f > /home/chronos/user/Downloads/losetup_output.txt
> chmod 777 /home/chronos/user/Downloads/losetup_output.txt
> ```
> 
> Then the output file will be in your Downloads folder which you can upload here. This is only necessary because I need to be able to see the exact spacing that's used by this quirky little implementation of `losetup` - I can't find any instance of this in the main util-linux repo.


There was no `/home/chronos/user/Downloads/`, but the output of `losetup -f` was so small that I can just type it here:

```
FINDING FREE!!!
/dev/loop12
```

I am on ChromeOS v130 and using the 'latest version' option in the script (I also spoofed my kernver to 1 with SH1MMER Legacy, developer mode unblocked)

**Comment by rainestorme** [comment] 2024-11-11 16:40
Yep, I found the patch - see [codesearch](https://source.chromium.org/chromiumos/chromiumos/codesearch/+/main:src/third_party/chromiumos-overlay/sys-apps/util-linux/files/CHROMIUM-losetup-autoclear.patch?q=%22FINDING%20FREE%22&ss=chromiumos%2Fchromiumos%2Fcodesearch). I can add a workaround in just a second.

**Comment by Packjackisback** [comment] 2024-11-11 17:06
Yep. Just head -n 2 and it should be working

**Comment by Packjackisback** [comment] 2024-11-11 17:10
My repo has the fix, I can make a pr if needed

**Closed** 2024-11-11 21:08 UTC
Labels: invalid
