### ISSUE TITLE
Configure policy-enforced restarts

### ISSUE THREAD

**Issue by Eboi47** [rainestorme/murkmod#94] opened 2024-10-14 06:10 UTC
**Is your feature request related to a problem? Please describe.**
Some schools require your chromebook to forcibly restart at a set date and time no matter what. It would be helpful if this could be bypassed or just disabled to avoid losing work from tabs reloading upon rebooting.

**Describe the solution you'd like**
It would be helpful if there was an option to enable, disable, or configure policy enforced restarts to be at a different time or date.

**Would this work better as a plugin or a built-in feature of murkmod?**
This might be something already configurable via Lilac, but that isn't a plugin yet.

**Comment by rainestorme** [comment] 2024-10-15 16:41
Good points - but this would be considered a duplicate of #60 (at least, I believe that's how forced restarts are controlled).

**Comment by rainestorme** [comment] 2024-11-11 14:41
Duplicate of #60.

**Closed by rainestorme** 2024-11-11 14:41 UTC
Labels: enhancement
