### ISSUE TITLE
custom bootsplash doesnt work

### ISSUE THREAD

**Issue by 10g1** [rainestorme/murkmod#80] opened 2024-08-26 09:09 UTC
- Board: dedede
 - Version: 126
- Installation method used: devmode vt2

when trying to change bootsplash it doesnt work and instead says it cannot replace or delete files
is there a fix to this? 
do i have to downgrade murkmod?

**Comment by inLnx** [comment] 2024-08-31 01:25
No you need to downgrade under 118. Newer Versions have a write patch

**Comment by rainestorme** [comment] 2024-09-11 22:26
I'll take a look at this in a few days.

**Comment by Eboi47** [comment] 2024-09-23 23:44
Weird, it works for me! I use version 119 though could it be related to v120+ having extra checks when booting?

**Comment by rainestorme** [comment] 2024-09-24 18:08
Alright, I'll mark this as invalid unless there's proof of it being reproducible.

**Comment by Eboi47** [comment] 2024-10-14 17:40
The murkmod bootsplash works, and the pre-made ones don't animate, and only freeze on the first frame, but still show up. It is when you attempt to make a bootsplash from your downloads that there are issues. It just won't work, perhaps there are certain requirements for resolution or file size that aren't mentioned?

**Comment by rainestorme** [comment] 2024-10-15 16:46
Well, first thing's first - you entered the wrong filename - it can't find the file to copy.

**Comment by rainestorme** [comment] 2024-11-12 14:24
Custom animated bootsplashes have always been iffy, so this will remain a wontfix for now.

**Closed** 2024-12-03 21:05 UTC
Labels: bug, invalid, wontfix, priority: low
