### ISSUE TITLE
Write protection error when using devmode installer.

### ISSUE THREAD

**Issue by Eboi47** [rainestorme/murkmod#84] opened 2024-09-15 22:57 UTC
**Describe the bug**
When using the Devmode installer, there will be an error complaining about having write protect on somewhere along the installation. 
For whatever reason, rebooting the Chromebook will make it act as a successfully murkmodded Chromebook, but some things are missing. 
However, if you run the Installer command again, it will work correctly without error.

**To Reproduce**
1. Open the terminal with CTRL+ALT+ ->
2. Log in as root and run the installer command
3. Do everything it says and wait.

**Expected behavior**
The Chromebook should install murkmod successfully the first time.

**Screenshots**
![PXL_20240915_224516462](https://github.com/user-attachments/assets/baa65cab-f574-4316-af11-a914042980e6)

**System (please complete the following information):**
 - Board [Dedede]
 - Version [v117]
- Installation method used [devmode installer]

**Additional context**
-When rebooting after error, murkmod will be missing plugins, emergency reverting, and various other things will be missing or broken.
-This does not actually mess up installation if you just run the installer again, but does mess it up if you only reboot.

**Comment by rainestorme** [comment] 2024-09-16 15:12
During installation, the installer tries to set your GBB flags to `0x8091` - it should just continue regardless if write-protect is enabled on your flash chip, but clearly it is not. This is indeed not the intended behavior. You're right, though - most preliminary assets will be installed to your system, and the rest can be repaired by rerunning the installer (through the update shortcut in mush).

**Closed** 2024-09-16 15:16 UTC
Labels: bug
